# Generated by Django 4.2.1 on 2023-05-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category_images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
