# Generated by Django 4.2.1 on 2023-05-04 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'verbose_name': 'main',
                'verbose_name_plural': 'Mains',
            },
        ),
    ]
