# Generated by Django 4.2.1 on 2023-05-05 03:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='address',
            field=models.CharField(default=1, max_length=256, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='comment',
            field=models.TextField(default=1, verbose_name='comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='phone_number',
            field=models.CharField(default=1, max_length=256, validators=[django.core.validators.RegexValidator(message='You should write +996[code][number]', regex='^(\\+996)\\d{9}$')], verbose_name='phone_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.product', verbose_name='product'),
        ),
    ]
